site:
  ip: 192.168.50.4
  mysql_database: wordpress
  mysql_username: root
  mysql_password: root
  wordpress_username: root
  wordpress_password: root
  wordpress_email: matthewkosloski@me.com
  wordpress_title: Meow